FROM docker.io/library/python:3.14-slim-trixie

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      git \
      wget \
 && rm -rf /var/lib/apt/lists/*
