"""File-backed per-app Shell environment configuration."""

from __future__ import annotations

import json
import os
import re
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .workspace_layout import ENV_DIRECTORY, ensure_workspace_directory


ENVIRONMENT_VERSION = 1
MAX_ENVIRONMENT_VARIABLES = 256
MAX_ENVIRONMENT_NAME_CHARS = 128
MAX_ENVIRONMENT_VALUE_CHARS = 65_536
MAX_ENVIRONMENT_TOTAL_CHARS = 262_144
MAX_ENVIRONMENT_RC_CHARS = 131_072
ENVIRONMENT_NAME_PATTERN = re.compile(
    rf"[A-Za-z_][A-Za-z0-9_]{{0,{MAX_ENVIRONMENT_NAME_CHARS - 1}}}\Z"
)
APP_ID_PATTERN = re.compile(r"[A-Za-z0-9_-]{16}\Z")
RESERVED_ENVIRONMENT_NAMES = {
    "HOME",
    "PATH",
    "TMPDIR",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "ALL_PROXY",
    "NO_PROXY",
    "http_proxy",
    "https_proxy",
    "all_proxy",
    "no_proxy",
    "LD_PRELOAD",
    "LD_LIBRARY_PATH",
    "PYTHONHOME",
    "PYTHONPATH",
    "BASH_ENV",
    "ENV",
    "SHELLOPTS",
    "CDPATH",
}


class EnvironmentConfigError(ValueError):
    """Stored or supplied environment configuration is invalid."""


@dataclass(frozen=True)
class EnvironmentConfig:
    variables: dict[str, str]
    rc: str
    updated_at: str | None = None

    @property
    def configured(self) -> bool:
        return bool(self.variables or self.rc)

    def public(self, *, include_values: bool) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "configured": self.configured,
            "variable_names": sorted(self.variables),
            "variable_count": len(self.variables),
            "rc_configured": bool(self.rc),
            "updated_at": self.updated_at,
        }
        if include_values:
            payload["variables"] = dict(sorted(self.variables.items()))
            payload["rc"] = self.rc
        return payload


class EnvironmentStore:
    """Atomic JSON storage inside one workspace's private env directory."""

    def __init__(self, workspace: Path):
        self.workspace = Path(workspace).resolve(strict=True)

    def _directory(self) -> Path:
        return ensure_workspace_directory(self.workspace, ENV_DIRECTORY)

    def _path(self, app_id: str) -> Path:
        if not APP_ID_PATTERN.fullmatch(app_id):
            raise EnvironmentConfigError("app_id must contain 16 URL-safe characters")
        return self._directory() / f"{app_id}.json"

    def _shell_path(self, app_id: str) -> Path:
        if not APP_ID_PATTERN.fullmatch(app_id):
            raise EnvironmentConfigError("app_id must contain 16 URL-safe characters")
        return self._directory() / f"{app_id}.rc"

    @staticmethod
    def _shell_quote(value: str) -> str:
        return "'" + value.replace("'", "'\"'\"'") + "'"

    @classmethod
    def _render_shell_rc(cls, config: EnvironmentConfig) -> bytes:
        lines = ["# Generated by OpenKapsel; edit through the environment API."]
        for name, value in sorted(config.variables.items()):
            lines.append(f"export {name}={cls._shell_quote(value)}")
        if config.rc:
            lines.extend(("# User-provided POSIX Shell initialization follows.", config.rc))
        return ("\n".join(lines).rstrip("\n") + "\n").encode("utf-8")

    @staticmethod
    def _atomic_write(path: Path, encoded: bytes, prefix: str) -> None:
        directory = path.parent
        temporary_name: str | None = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="wb",
                dir=directory,
                prefix=prefix,
                suffix=".tmp",
                delete=False,
            ) as handle:
                temporary_name = handle.name
                os.fchmod(handle.fileno(), 0o600)
                handle.write(encoded)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary_name, path)
            temporary_name = None
            path.chmod(0o600)
            directory_fd = os.open(directory, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
        finally:
            if temporary_name is not None:
                try:
                    Path(temporary_name).unlink()
                except FileNotFoundError:
                    pass

    @staticmethod
    def validate(variables: Any, rc: Any) -> EnvironmentConfig:
        if not isinstance(variables, dict):
            raise EnvironmentConfigError("variables must be a JSON object")
        if len(variables) > MAX_ENVIRONMENT_VARIABLES:
            raise EnvironmentConfigError(
                f"variables cannot contain more than {MAX_ENVIRONMENT_VARIABLES} entries"
            )
        normalized: dict[str, str] = {}
        total_chars = 0
        for raw_name, raw_value in variables.items():
            if not isinstance(raw_name, str) or not ENVIRONMENT_NAME_PATTERN.fullmatch(raw_name):
                raise EnvironmentConfigError(
                    f"environment variable names must match {ENVIRONMENT_NAME_PATTERN.pattern}"
                )
            if raw_name.startswith("OPENKAPSEL_") or raw_name in RESERVED_ENVIRONMENT_NAMES:
                raise EnvironmentConfigError(
                    f"environment variable is reserved by OpenKapsel: {raw_name}"
                )
            if not isinstance(raw_value, str):
                raise EnvironmentConfigError(
                    f"environment variable values must be strings: {raw_name}"
                )
            if "\x00" in raw_value:
                raise EnvironmentConfigError(
                    f"environment variable values must not contain NUL: {raw_name}"
                )
            if len(raw_value) > MAX_ENVIRONMENT_VALUE_CHARS:
                raise EnvironmentConfigError(
                    f"environment variable value exceeds {MAX_ENVIRONMENT_VALUE_CHARS} characters: {raw_name}"
                )
            total_chars += len(raw_name) + len(raw_value)
            normalized[raw_name] = raw_value
        if total_chars > MAX_ENVIRONMENT_TOTAL_CHARS:
            raise EnvironmentConfigError(
                f"environment variables exceed {MAX_ENVIRONMENT_TOTAL_CHARS} total characters"
            )
        if not isinstance(rc, str):
            raise EnvironmentConfigError("rc must be a string")
        if "\x00" in rc:
            raise EnvironmentConfigError("rc must not contain NUL")
        if len(rc) > MAX_ENVIRONMENT_RC_CHARS:
            raise EnvironmentConfigError(
                f"rc exceeds {MAX_ENVIRONMENT_RC_CHARS} characters"
            )
        return EnvironmentConfig(dict(sorted(normalized.items())), rc)

    def load(self, app_id: str) -> EnvironmentConfig:
        path = self._path(app_id)
        if path.is_symlink():
            raise EnvironmentConfigError("environment configuration must not be a symlink")
        try:
            raw = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            return EnvironmentConfig({}, "")
        if len(raw) > MAX_ENVIRONMENT_TOTAL_CHARS + MAX_ENVIRONMENT_RC_CHARS + 65_536:
            raise EnvironmentConfigError("stored environment configuration is too large")
        try:
            payload = json.loads(raw)
        except (UnicodeError, json.JSONDecodeError) as exc:
            raise EnvironmentConfigError("stored environment configuration is invalid JSON") from exc
        if not isinstance(payload, dict) or payload.get("version") != ENVIRONMENT_VERSION:
            raise EnvironmentConfigError("stored environment configuration has an unsupported version")
        config = self.validate(payload.get("variables", {}), payload.get("rc", ""))
        updated_at = payload.get("updated_at")
        if updated_at is not None and not isinstance(updated_at, str):
            raise EnvironmentConfigError("stored environment updated_at is invalid")
        return EnvironmentConfig(config.variables, config.rc, updated_at)

    def replace(self, app_id: str, variables: Any, rc: Any) -> EnvironmentConfig:
        config = self.validate(variables, rc)
        updated_at = datetime.now(timezone.utc).isoformat()
        result = EnvironmentConfig(config.variables, config.rc, updated_at)
        path = self._path(app_id)
        payload = {
            "version": ENVIRONMENT_VERSION,
            "updated_at": updated_at,
            "variables": result.variables,
            "rc": result.rc,
        }
        encoded = (json.dumps(payload, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode(
            "utf-8"
        )
        self._atomic_write(path, encoded, f".{app_id}.")
        self._atomic_write(
            self._shell_path(app_id),
            self._render_shell_rc(result),
            f".{app_id}.rc.",
        )
        return result

    def shell_file(self, app_id: str) -> Path | None:
        config = self.load(app_id)
        path = self._shell_path(app_id)
        if not config.configured:
            if path.is_symlink():
                raise EnvironmentConfigError("Shell environment file must not be a symlink")
            try:
                path.unlink()
            except FileNotFoundError:
                pass
            return None
        self._atomic_write(path, self._render_shell_rc(config), f".{app_id}.rc.")
        return path

    def clear(self, app_id: str) -> bool:
        path = self._path(app_id)
        if path.is_symlink():
            raise EnvironmentConfigError("environment configuration must not be a symlink")
        removed = False
        for candidate in (path, self._shell_path(app_id)):
            if candidate.is_symlink():
                raise EnvironmentConfigError("environment configuration must not be a symlink")
            try:
                candidate.unlink()
                removed = True
            except FileNotFoundError:
                pass
        return removed
